### ISSUE TITLE
ToolStick F330DC: usb_interrupt_read in read_usb returned -110 : Connection timed out exiting now

### ISSUE THREAD

**Issue by lcafaro** [paragonRobotics/ec2-new#11]
Hello,

I'm trying to get a ToolStick Starter Kit (TOOLSTICK850-B-SK) to work under Linux Mint.

After compiling the toolchain from source I can successfully list adapters:
```
[lorenzo@elisa ~/ec2-new/src/ec2tools]$ sudo ./ec3adapters 
List of Silicon Labs USB debug adapters found:
port		Device			Manufacturer		Friendly Name
USB:TS004A3113	ToolStick	Silicon Laboratories	ToolStick F330 DC
```

Sadly there's no way to actually talk with the device. Firmware flashing fails:

```
[lorenzo@elisa ~/ec2-new/src/ec2tools]$ sudo ./ec2writeflash /home/lorenzo/Desktop/F85x_Blinky.hex --mode=C2 --port USB
ToolStick F330 DC debugger, no version information
/home/lorenzo/ec2-new/src/ec2tools/.libs/lt-ec2writeflash:ec2drv.c:2046: 
usb_interrupt_read in read_usb returned -110 : Connection timed out
Exiting now
/home/lorenzo/ec2-new/src/ec2tools/.libs/lt-ec2writeflash:ec2drv.c:2046: 
usb_interrupt_read in read_usb returned -110 : Connection timed out
```

... and so does `ec2test`:
```
[lorenzo@elisa ~/ec2-new/src/ec2tools]$ sudo ./ec2test-any --port USB
Testing device / debugger connected to 'USB'
*********************************************************************
* WARNING: Auto detection of mode may cause initialisation sequence *
* to differ significantly from the SiLabs IDE.                      *
* In the case of problems specify --mode=C2 or --mode=JTAG          *
*********************************************************************

ToolStick F330 DC debugger, no version information
/home/lorenzo/ec2-new/src/ec2tools/.libs/lt-ec2test-any:ec2drv.c:2046: 
usb_interrupt_read in read_usb returned -110 : Connection timed out
exiting now
/home/lorenzo/ec2-new/src/ec2tools/.libs/lt-ec2test-any:ec2drv.c:2046: 
usb_interrupt_read in read_usb returned -110 : Connection timed out
```

Is this programmer supported at all?

Thanks!

**Comment by paragonRobotics** [comment]
Although toolstick support was "theoretically" added before this code was forked, I have only personally tested on EC3 and EC2 programmers. I'm guessing there are probably plenty of bugs in the toolstick support that was added, so it may be difficult to get it running reliably.

Do you have the option of using a EC3 debugger for your work?

**Comment by lcafaro** [comment]
Hi,

sadly I have no EC3 debugger available (it's my first experience with Silabs and I've just bought their starter kit).

Anyway, I've opened a case to their 8-bit MCU support team, since I've double checked by trying to program a chip via their Windows IDE and I get "Incorrect firmware version download" there too. Looks like it might be an hardware issue then, I'll update this issue in case I get any update.

Thanks for now

**Comment by lcafaro** [comment]
Hi,

Silabs confirmed an hardware issue on the ToolStick and they've shipped me a replacement which will arrive in 3 weeks, so I'm closing this for now.

Thanks
